import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { RouterProvider } from "@/components/router-provider";
import "@/app/styles/globals.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { MainNavWrapper } from "@/components/navigation/main-nav-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className="scroll-smooth"
      data-scroll-behavior="smooth"
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
      >
        <NextTopLoader showSpinner={false} color="#0ea5e9" shadow={false} />
        <RouterProvider>
          <NuqsAdapter>{props.children}</NuqsAdapter>
        </RouterProvider>
      </body>
    </html>
  );
}
